server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  config:
    import:
      - application_qa.yaml
      - application_prod.yaml
  profiles:
    active:
      - qa

build:
  version: "3.0"

accounts:
  message: "Welcome to the Accounts Service in Local Environment"
  contactDetails:
    email: "johny@gmail.com"
    name: "John Doe"
  onCallSupport:
    - (800) 123-4567
    - (800) 765-4321