spring:
  config:
    activate:
      on-profile: qa

build:
  version: "2.0"

accounts:
  message: "Welcome to the Accounts Service in QA Environment"
  contactDetails:
    email: "sarad@gmail.com"
    name: "Sara Doe"
  onCallSupport:
    - (600) 123-4567
    - (600) 765-4321