spring:
  config:
    activate:
      on-profile: prod

build:
  version: "1.0"

cards:
  message: "Welcome to the Cards Service in Production Environment"
  contactDetails:
    email: "evad@gmail.com"
    name: "Eva Doe"
  onCallSupport:
    - (200) 123-4567
    - (200) 765-4321